### PR TITLE
Add CFC to emissions reporting

### PR DESCRIPTION
**Pull request by jayfuhrman**
Add reporting category for CFC emissions

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Thank you, that looks quite straightforward - will merge once approved by another person from the emissions-team

**Comment by gidden** [comment]
Thanks @jayfuhrman - just curious, how did you decide on CFC-12 as the common equivalent?

**Comment by jayfuhrman** [comment]
@gidden my understanding is that and CFC-11 are the most common CFCs

**Comment by gidden** [comment]
@ssmithClimate do you have a common CFC equivalent in CEDS, or any recommendations for such? thanks!

**Comment by ssmithClimate** [comment]
But I suspect Kalyn can point you to those details in Hector, including for future forcing, and you can calculate the CO2eq using whatever GWP basis you want.

**Comment by gidden** [comment]
for lack of a better approach, I approve!

**Pull request merged**
