### PR TITLE
fix occurence of tag in description different from use in variable

### PR DESCRIPTION
**Pull request by orichters**
- fixes https://github.com/IAMconsortium/common-definitions/issues/132

### CODE REVIEW

**Review by phackstock — COMMENTED** [review]
@orichters, thanks for the fix, was the occurrence of `{Non-Energy Sector with Source}` a mistake in the first place?
If so, good to merge from my side.

**Comment by orichters** [comment]
I think this was an error by Daniel where he added the "with Source" part at the wrong position: https://github.com/IAMconsortium/common-definitions/commit/4f77be867cfa400c41ad826a64ad32e5b13d18ca#diff-fcd91785e0d03088310cced930c54d086a62bf30ae1c102275607adf963ff65aL26

**Comment by phackstock** [comment]
Ah ok, thanks for the clarification. If it's not urgent, I'd rather wait for Daniel before we merge.

**Comment by orichters** [comment]
@danielhuppmann: Can we merge this and fix this error?

**Review by danielhuppmann — APPROVED** [review]
Thanks for the fix, @orichters

**Pull request merged**
