### PR TITLE
add SDG template from SHAPE

### PR DESCRIPTION
**Pull request by bs538**
First draft of SDG template, copied as is from SHAPE project SDG template.

Note: this SDG template was used together with the NAVIGATE template, therefore SDG-relevant variables already contained in the NAVIGATE template are not listed again here. Once the other sub-templates are developed a bit further, we need a round of checking them and cross-tagging SDG-relevant variables.

### CODE REVIEW

**Comment by bs538** [comment]
@phackstock the failing checks are due to weights that are not part of the SDG template (were part of the NAVIGATE template, would end up in other sub-templates here I assume). So this cannot be fixed within the SDG template. Is there already a standard procedure for dealing with this?

**Comment by danielhuppmann** [comment]
@bs538, I started a PR for adding the GDP variables, see #54. For the other missing variables, please reach out to the relevant other topical groups and/or the coordinators.

I suggest to split up your PR into several smaller PRs by topical area (eg., health, population) so that uncontroversial PRs can be merged quickly and other topical groups can be looped in as necessary (e.g., energy).

Also, please review the variables such that they conform to the guidelines at https://docs.ece.iiasa.ac.at/iamc/variable.html, in particular adding whitespaces between words and using capitalization.

**Comment by bs538** [comment]
Thanks @danielhuppmann . Will tackle the naming issues.
I'm not so convinced about splitting into multiple PR by topic, as several topical areas are affected by missing weights. Most missing weights are standard variables from the NAVIGATE template, the issue is just that the respective sub-groups that this variables would fall into now haven't added them yet, right? So pragmatically, can I just comment the variables with missing weights for now (does the processing of the yaml accept this?) and re-include them later?

**Comment by realxinzhao** [comment]
This might be a good place for a few quick food variables related clarification questions:
It seems the food related variables were improved/clarified (compared to AR6). E.g., the food energy supply was removed, and food demand was changed to food availability. 

1. food waste 
It seems there is `Food Waste|Per capita`. It that the difference between availability and intake? If yes, should we use `Food|Food Waster` for consistency? And may be clarify the calculation in the definition?

2. Price|Agriculture|Livestock|Index
The price variable was under `economics` for AR6. We were also wondering if we should include them under Land/AFOLU. It seems the livestock one was included in SDG. Did you mean to also include crop prices? 

3. Land Cover|Forest|Natural Forest|*
Similarly, there are 2 land cover variables here in SDG. 

Looping @flohump in. 

Thanks!
Xin

**Comment by bs538** [comment]
@realxinzhao thanks for these points, sorry for the slightly slow response. Will give you my thoughts without being land/food expert. 

>     1. food waste
>        It seems there is `Food Waste|Per capita`. It that the difference between availability and intake? If yes, should we use `Food|Food Waster` for consistency? And may be clarify the calculation in the definition?
Yes, that sounds right.
> 
>     2. Price|Agriculture|Livestock|Index
>        The price variable was under `economics` for AR6. We were also wondering if we should include them under Land/AFOLU. It seems the livestock one was included in SDG. Did you mean to also include crop prices?

Make sense to have it in Land/AFOLU in my view. It shows up here rather for historical reasons. We included everything in this SDG template that we wanted to report in SHAPE, but that was missing in the NAVIGATE template (in a pre-final version). Happy about every variable that can be moved into a topical area.
> 
>     3. Land Cover|Forest|Natural Forest|*
>        Similarly, there are 2 land cover variables here in SDG.
see above.

@flohump can you complement/correct? For now I haven't tackled these in my further commits.  would you take over for this?

**Comment by bs538** [comment]
@danielhuppmann I went over the naming to adhere to the new conventions (of course some edge cases, but generally OK I hope).

I resolved the failing tests by temporarily switching off the region aggregation for the variables in question. The original weights are preserved as comments, so aggregation can easily be re-added once the respective weight variables have been added by the subgroups. (All are variables that were present in NAVIGATE template I believe, so I do expect them to show up eventually. However, I don't think we as SDG group can/should take over the job of chasing down the all the sub-groups.)

As today is my last day before around 2.5 months of parental leave, I would suggest to merge this first stab now (unless there are further pressing issues). The discussion about the food/land variables and about the missing weights could be moved into a separate issue (and assigned to respective groups) so that the points are not lost.

Would ask @VassilisDaioglou and @shinichirofujimoriKU to take over from here.

**Comment by danielhuppmann** [comment]
Closing in favor of #73

**Pull request closed without merging**
