### PR TITLE
Variables for agricultural production and consumption

### PR DESCRIPTION
**Pull request by danielhuppmann**
This PR is for discussion of adding variables for agricultural production and consumption.

I'm wondering whether to copy over the duplications from the ENGAGE variable template, in particular:

```
Agricultural Demand|Crops
Agricultural Demand|Crops|...
Agricultural Demand|Energy
Agricultural Demand|Energy|Crops
Agricultural Demand|Energy|Crops|1st generation
Agricultural Demand|Energy|Crops|2nd generation
Agricultural Demand|Energy|Residues
Agricultural Demand|Livestock
Agricultural Demand|Livestock|...
Agricultural Demand|Non-Energy
Agricultural Demand|Non-Energy|Crops
Agricultural Demand|Non-Energy|Crops|...
Agricultural Demand|Non-Energy|Livestock
Agricultural Demand|Non-Energy|Livestock|...
```
where `...` indicates distinction by Feed, Food and Other...

Comparing this to the AGMIP variable template, the primary distinction into energy vs. non-energy seems to run counter to the agricultural-modeling logic - a structure "Crops -> Energy vs. Other Uses" would seem more in line with the AGMIP template.

Any thoughts @IAMconsortium/common-definitions-land @IAMconsortium/common-definitions-coordination?

### CODE REVIEW

**Comment by flohump** [comment]
I started a discussion about re-structering land-related variables about 6 month ago with colleagues from PNNL (https://github.com/realxinzhao and https://github.com/kanishkan91) in a forked repo: https://github.com/flohump/common-definitions/blob/AFOLU_temp/temp/AgLUVariables.xlsx
The .xlsx file includes our tentative proposal back then. 
Based on an e-mail from @volker-krey we were expecting that a meeting with the full group would have be scheduled in spring for discussing our proposal and to sort out cross-sector questions like water. But this meeting was never scheduled...
I'm happy to resume this discussion after my holidays in the beginning of September.

**Comment by danielhuppmann** [comment]
Thanks @flohump for pointing me to your previous discussion, apologies that the process for setting up sector-calls wasn't followed through...

I will start a set of PRs for your variable proposals (one per top-level variable or category) to have a more targeted discussion.

About the renaming of variables: yes, this is an issue when comparing different datasets, but
- we have already implemented several renamings for consistency and acuracy in this common variable template, for example going from carbon removal to carbon management in the final-energy demand variables
- we are tracking renamings in this repository using attributes of former projects variables, see https://github.com/IAMconsortium/common-definitions/blob/4f77be867cfa400c41ad826a64ad32e5b13d18ca/definitions/variable/energy/final-energy.yaml#L94
- we will implement an automated transfer-and-renaming-workflow to minimize disruption and facilitate comparison between legacy and new projects

As a consequence, it's better to do all renamings now rather than carry bad design forward.

**Comment by danielhuppmann** [comment]
Thanks @flohump, I implemented the second part (agricultural production) first, a few questions:
1. What are the subcategories of livestock (or can we ignore that for now)?
2. You call it oil crops, in the AGMIP template I see "oilseeds" - should this be harmonized?
3. Should we add an "Agricultural Production|Other" category?
4. Which of the agmip types are included in Cereals? Wheat, coarse grain - what about rice, vegetables, etc.? Or do we ignore all of that for now?

**Comment by danielhuppmann** [comment]
And I also added the agricultural-demand variables, but not (yet) the subcategories - let's leave that for another PR (later this year).

**Comment by danielhuppmann** [comment]
Merging this so we can send out an initial variable template to all modeling teams for the SSP-ScenarioMIP process. Please start an issue or open a new PR if you think that I made a mistake in this implementation, or to add more granularity.

**Comment by flohump** [comment]
@danielhuppmann I have important additions to the mapping. I will make a new PR. Thanks for making the link to the SSP-ScenarioMIP process.

**Pull request merged**
