### PR TITLE
Add gross-carbon-removal variables

### PR DESCRIPTION
**Pull request by danielhuppmann**
Add variables for carbon-removal technologies as requested (with some slight streamlining and simplifications).

### CODE REVIEW

**Comment by danielhuppmann** [comment]
As mentioned also in the email to @IAMconsortium/common-definitions-emissions, I find it odd that removal by geological storage is not included in this list...

**Comment by jayfuhrman** [comment]
Looks good.  Suggested definitions for 

Afforestation: Carbon dioxide (CO2) removed from the atmosphere by increasing forested land area and thereby increasing vegetation and soil carbon stocks. 

Agroforestry: Carbon dioxide (CO2) removed from the atmosphere by integrating trees into crop and pasture lands to increase vegetation and soil carbon stocks

Biochar: Carbon dioxide (CO2) removed from the atmosphere through the conversion of biomass to recalcitrant carbon via pyrolysis and its subsequent application to croplands to increase soil carbon stocks

Soil carbon management: Carbon dioxide (CO2) removed from the atmosphere by increasing organic carbon content through no or low-till agricultural practices, or manure or compost application.  Note that biochar should be reported as its own category

## Note that not all models have capability to easily report gross as opposed to net CO2 emissions from land-use change so we may need to have a broader discussion on how to handle this

**Comment by danielhuppmann** [comment]
Thanks @jayfuhrman, extended the description of the removal-options per your comment.

**Comment by jayfuhrman** [comment]
We should add DACCS and BECCS to carbon removal variables (and synthetic fuels) as well.  @strefler @gidden

**Review by jayfuhrman — APPROVED** [review]

**Review by jayfuhrman — CHANGES_REQUESTED** [review]
If everyone is OK with the top-level descriptions of CDR in carbon-removal.yaml, suggest mostly following SOCDR variables in https://github.com/iiasa/socdr-workflow/blob/main/definitions/variable/tag_conventional-cdr-methods.yaml and https://github.com/iiasa/socdr-workflow/blob/main/definitions/variable/tag_conventional-cdr-methods.yaml.  So the tag_carbon-removal.yaml file would look something like this:

- Carbon-Removal Option

    - Forestry:
        description: all forestry-related carbon dioxide removal methods, in particular
          afforestation, reforestation, agroforestry and improved forest management
    - Afforestation and Reforestation:
        description: afforestation and reforestation
        note: This is a subcategory of "Forestry"
    - Agroforestry:
        description: agroforestry
        note: This is a subcategory of "Forestry"
    - Improved Forest Management:
        description: improved forest management
        note: This is a subcategory of "Forestry"
    - Peatland and Wetland Restoration:
        description: restoration of peat and coastal wetlands, including "Blue Carbon"
    - Peatland Restoration:
        description: restoration of peatlands
        note: This is a subcategory of "Peatland and Wetland Restoration"
    - Coastal Wetland Restoration:
        description: restoration of coastal wetlands, including "Blue Carbon"
        note: This is a subcategory of "Peatland and Wetland Restoration"
    - Soil Carbon Sequestration:
        description: soil carbon sequestration in croplands and graslands
    - Durable Wood Products:
        description: use of durable wood products and building elements
    - Biochar:
        description: use of biochar
    - Bio-Oil Storage:
        description: use of bio-oil
    - Bioenergy with CCS and Direct Air Capture with CCS:
        description: use of bioenergy and direct air capture in combination with
          carbon-capture and sequestration (CCS)
    - Bioenergy with CCS:
        description: use of bioenergy in combination with carbon-capture and
          sequestration (CCS)
    - Direct Air Capture with CCS:
        description: direct air capture in combination with carbon-capture and
          sequestration (CCS)
    - Enhanced Weathering:
        description: application of alkalinity to increase CO2 uptake on land
    - Mineral Products:
        description: use of mineral products for carbon sequestration
    - Biomass Burial:
        description: burial of biomass on land
    - Ocean Fertilization:
        description: ocean fertilization and artificial upwelling
    - Biomass Sinking:
        description: sinking of biomass in the ocean
    - Ocean Alkalinity Enhancement:
        description: ocean alkalinity enhancement
    - Direct Ocean Capture:
        description: direct capture of CO2 from the ocean in combination with
          carbon sequestration (CCS)

**Comment by gidden** [comment]
Hi @jayfuhrman - very much agree with your approach. We have an overview figure here: https://www.stateofcdr.org/s/SoCDR-2Ed-Fig-14-for-website.pdf

Would you mind adapting this PR to include the categories you mentioned, including tiers (e.g., Forestry|Aforestation) and cross check the final SoCDR list? Happy to approve after that!

**Comment by danielhuppmann** [comment]
Thanks @gidden.

I implemented the changes in line with the State of CDR variables, with the following changes:
- I did not (yet) include the sub-categories of forestry and of peatland & (coastal) wetland restoration - not sure if any models can even report at that level of detail?
- Not all "Materials" variables in your initial proposal are included in SoCDR, in particular plastics.
  ```yaml
    - Materials:
        description: use of long-lived materials with centennial to millennial residence times
    - Materials|Cement:
        description: use of cement
    - Materials|Plastics:
        description: use of long-lived plastics
    - Materials|Timber:
        description: use of long-lived timber
    - Materials|Other:
        description: use of other long-lived materials
   ```
  Should this be added? And is "Durable Wood Products" really a *removal* option? Depends on the expected lifetime, I guess - should this be clarified?

Also, I notice that there is no "Geological Storage" variable, this is only the aggregate of BECCS and DACCS, and there is no way to report non-bioenergy process-based CCS. Is that really the way to go forward for IAM reporting?

**Comment by gidden** [comment]
Hi @danielhuppmann - thanks!

> I did not (yet) include the sub-categories of forestry and of peatland & (coastal) wetland restoration - not sure if any models can even report at that level of detail?

I think we do want them in as these are methods actively being investigated and will also potentially show up in historical datasets as well.

> Should this be added? And is "Durable Wood Products" really a removal option? Depends on the expected lifetime, I guess - should this be clarified?

Yes, we should keep plastics. However, that is more a CCU/S than CDR (depending on how the plastics are disposed). Yes, DWP are a short-lived CDR option. In principle, teams should take care to account for the duration and provide carbon flux returning to the atmosphere also in this variable. Maybe useful to include in the description?

**Review by gidden — APPROVED** [review]
This looks good to me. Suggest we deal with other carbon management in a different PR.

**Comment by danielhuppmann** [comment]
Merging this so that it can be considered in the reporting for the initial SSP-ScenarioMIP submission process.

**Pull request merged**
