### PR TITLE
Rename employment variables to "Labor Force" category

### PR DESCRIPTION
**Pull request by danielhuppmann**
As a follow-up to #57, this PR renames the Employment/Unemployment variables from the population-category to a new top-level category "Labor Force".

@IAMconsortium/common-definitions-macro-economy, looking at the description of the variables introduce in #57, it said that "Not Active" are people outside of the working-age range. However, [this definition](https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:People_outside_the_labour_force#:~:text=A%20person%20is%20outside%20the,is%20neither%20employed%20nor%20unemployed.) states that "Outside the Labor Force" includes all people not actively looking for work, which may include working-age people.

Please clarify or make your categorization complete by adding a category for inactive people of working age.

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Ping @FlorianLeblancDr, please double-check whether the description of "Not Active" should be changed to be in line with ILO definitions.

**Comment by FlorianLeblancDr** [comment]
Hi Daniel,
Sorry for the long delay.
Thanks for checking, indeed Inactive does not only means not being at the age of working according to the ILO.

I made some edits.

I will see later if those definitions are robust to several definitions of unemployment (more for tier 2 / 3 var.)

**Comment by danielhuppmann** [comment]
Thanks @FlorianLeblancDr - just to be clear, you wrote "I made some edits", but it's not clear to me where you made them?

**Comment by FlorianLeblancDr** [comment]
@danielhuppmann Directly on Github here:
[https://github.com/IAMconsortium/common-definitions/pull/94/files](https://github.com/IAMconsortium/common-definitions/pull/94/files)
File labor-force.yaml

**Comment by danielhuppmann** [comment]
Thanks @FlorianLeblancDr, there was some formatting mix-up in your suggestions, so I revised them a bit further. Please approve if this is ready to be merged (a.k.a. good enough for now).

**Review by FlorianLeblancDr — APPROVED** [review]

**Comment by FlorianLeblancDr** [comment]
All good to me, thanks for the edits @danielhuppmann

**Pull request merged**
